import { ContactForm } from '@/components/ContactForm';
import { PublicShell } from '@/components/PublicShell';
import { SERVICES,SPA_INFO,TEAM_MEMBERS } from '@/data/spaData';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
const titles:Record<string,string>={about:'A thoughtful approach to care',services:'Explore our treatments',team:'Meet the concept team',locations:'Our concept locations',contact:'Start a conversation',privacy:'Privacy notice','booking-policy':'Booking policy'};
export function generateStaticParams(){return Object.keys(titles).map(section=>({section}));}
export async function generateMetadata({params}:{params:Promise<{section:string}>}){const {section}=await params;return {title:`${titles[section]??'Not found'} | Lumina`,description:'Lumina Med Spa is a fictional portfolio demonstration. Explore sample treatments and a working booking platform.'};}
export default async function Page({params}:{params:Promise<{section:string}>}){
 const {section}=await params;if(!titles[section])notFound();
 return <PublicShell title={titles[section]}>
  {section==='about'&&<div className="max-w-3xl space-y-5 text-lg leading-relaxed"><p>Lumina Med Spa is a fictional business created to demonstrate appointment booking, customer management, and business automation.</p><p>The visual concept combines calm spaces with clear, practical service information. All provider biographies, testimonials, addresses, and treatment descriptions are illustrative. They are not medical advice or claims of actual results.</p><Link href="/services" className="action-button inline-block">Explore sample treatments</Link></div>}
  {section==='services'&&<><p>Illustrative treatments and pricing. The booking flow displays the currently configured services and confirmed commercial values.</p><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{SERVICES.map(s=><Link key={s.id} href={`/services/${s.id}`} className="bg-white rounded-3xl border overflow-hidden"><Image src={s.image} alt={s.name} width={640} height={420} className="w-full h-56 object-cover"/><div className="p-6 space-y-3"><h2 className="font-serif text-2xl">{s.name}</h2><p>{s.tagline}</p><p className="text-sm">Sample price {s.price} · {s.duration}</p></div></Link>)}</div></>}
  {section==='team'&&<><p>Fictional provider profiles and sample credentials for this portfolio concept.</p><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{TEAM_MEMBERS.map(p=><Link key={p.id} href={`/team/${p.id}`} className="bg-white border rounded-3xl overflow-hidden"><Image src={p.avatar} alt={`Concept portrait for ${p.name}`} width={500} height={500} className="w-full h-64 object-cover"/><div className="p-6"><h2 className="font-serif text-2xl">{p.name}</h2><p>{p.title}</p></div></Link>)}</div></>}
  {section==='locations'&&<div className="rounded-3xl border bg-white p-8 space-y-4 max-w-2xl"><h2 className="text-2xl font-serif">Beverly Hills concept location</h2><p>{SPA_INFO.address}</p><p>This is an illustrative address, not an operating clinic.</p>{SPA_INFO.hours.map(h=><p key={h.days}>{h.days}: {h.hours}</p>)}<Link href="/book" className="underline">Check configured locations and availability</Link></div>}
  {section==='contact'&&<ContactForm/>}
  {section==='privacy'&&<article className="max-w-3xl space-y-5 leading-relaxed"><p>This is a portfolio demonstration. Use fictitious contact details and never submit medical records, sensitive health information, or real payment card details.</p><h2 className="text-2xl font-serif">Information handled by the application</h2><p>Booking and contact forms store the details you submit, appointment selections, consent choices, and operational history. Staff access is restricted by role. Session cookies support staff authentication and secure account recovery.</p><h2 className="text-2xl font-serif">Service providers</h2><p>When configured, Supabase stores application data, Stripe handles payments, Google Calendar synchronizes appointments, and email or messaging providers deliver consented notifications. Card details are entered on Stripe rather than stored by this application.</p><h2 className="text-2xl font-serif">Your choices</h2><p>Email and SMS notifications are optional. Private booking links allow access to a single appointment. Keep these links confidential. Use the contact form to request data access, correction, or deletion from the operator. An operating business must establish retention periods and publish its own reviewed notice before collecting real customer data.</p></article>}
  {section==='booking-policy'&&<article className="max-w-3xl space-y-5 leading-relaxed"><p>Appointments are available only for configured services, locations, and providers. Times are displayed in the location timezone. Availability is rechecked when you reserve and confirm.</p><h2 className="text-2xl font-serif">Reservations and deposits</h2><p>A temporary hold reserves a selected slot for up to 45 minutes. A required deposit is displayed before checkout. An appointment requiring payment is confirmed only when the application receives verified payment confirmation.</p><h2 className="text-2xl font-serif">Changes and cancellations</h2><p>The applicable notice period is shown during booking. Use your private manage-booking link before that cutoff to cancel or choose another available time. A failed reschedule preserves the original appointment. Eligible cancellations queue a refund of the captured deposit; bank processing times vary.</p><h2 className="text-2xl font-serif">Portfolio use</h2><p>This fictional business does not deliver clinical services. No medical outcomes are promised. Test payment mode and fictitious details should be used when demonstrating this project.</p></article>}
 </PublicShell>;
}
