'use client';
import { api } from '@/lib/api-client';
import { useEffect,useState } from 'react';
type Lead = { id:string; full_name:string; email:string; message:string; status:string; assigned_to:string|null; appointment_id:string|null };
type Task = { id:string; title:string; due_at:string|null; status:string };
type Activity = { id:string; lead_id:string; description:string; created_at:string };
type Data = { leads?:Lead[]; tasks?:Task[]; activities?:Activity[]; members?:{user_id:string;role:string}[]; byCurrency?:Record<string,number>; statuses?:Record<string,number>; providers?:{name:string;appointments:number}[]; services?:{name:string;appointments:number}[]; leadCount?:number; converted?:number; appointmentCount?:number };
const stages=['new','contacted','qualified','appointment_booked','converted','lost'];
export function OperationsTab({ resource }: { resource:'leads'|'tasks'|'reports' }) {
  const [data,setData]=useState<Data>({}); const [error,setError]=useState('');
  const [busy,setBusy]=useState(false);const [reload,setReload]=useState(0);const [search,setSearch]=useState('');
  const [selected,setSelected]=useState<Lead|null>(null);
  useEffect(()=>{let active=true;api<Data>(`/api/crm/${resource}`).then(r=>{if(active){setData(r);setError('');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[resource,reload]);
  async function update(input:unknown) {
    setBusy(true);setError('');
    try {await api(`/api/crm/${resource}`,input);setReload(v=>v+1);setSelected(null);}
    catch(e){setError(e instanceof Error?e.message:'The update failed.');}finally{setBusy(false);}
  }
  return <section className="booking-form space-y-5"><h2 className="text-3xl font-serif capitalize">{resource}</h2>
    {error&&<p role="alert" className="bg-red-50 text-red-800 p-4 rounded-xl">{error} <button className="underline" onClick={()=>setReload(v=>v+1)}>Retry</button></p>}
    {resource==='reports'&&<><p>Operational totals for the last 30 days. Revenue is captured payments minus refunds, grouped by currency.</p><div className="grid gap-4 sm:grid-cols-3">{Object.entries(data.byCurrency??{}).map(([currency,amount])=><div key={currency} className="rounded-2xl border bg-white p-5"><h3>Net captured ({currency.toUpperCase()})</h3><p className="text-2xl">{new Intl.NumberFormat('en-US',{style:'currency',currency}).format(amount/100)}</p></div>)}<div className="rounded-2xl border bg-white p-5">Appointments<p className="text-2xl">{data.appointmentCount??0}</p></div>{Object.entries(data.statuses??{}).map(([status,count])=><div className="rounded-2xl border bg-white p-5" key={status}>{status.replaceAll('_',' ')}<p className="text-2xl">{count}</p></div>)}</div></>}
    {resource==='reports'&&<div className="grid gap-5 sm:grid-cols-2">{(['providers','services'] as const).map(group=><div key={group} className="rounded-xl border bg-white p-5"><h3 className="capitalize font-semibold">{group}</h3>{data[group]?.map(row=><p key={row.name}>{row.name}: {row.appointments}</p>)}</div>)}</div>}
    {resource==='leads'&&<><label>Search leads<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or email" /></label><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{stages.map(stage=><div key={stage} className="rounded-2xl border bg-stone-50 p-4"><h3 className="font-semibold capitalize mb-4">{stage.replaceAll('_',' ')}</h3>{(data.leads??[]).filter(l=>l.status===stage&&`${l.full_name} ${l.email}`.toLowerCase().includes(search.toLowerCase())).map(l=><button className="block w-full text-left rounded-xl border bg-white p-4 mb-3" key={l.id} onClick={()=>setSelected(l)}><strong>{l.full_name}</strong><span className="block break-all text-sm">{l.email}</span></button>)}</div>)}</div>
      {selected&&<form className="rounded-2xl border bg-white p-5 space-y-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void update({id:selected.id,status:f.get('status'),assigned_to:f.get('assigned_to')||null,note:f.get('note'),appointment_id:f.get('appointment_id')||null});}}><h3 className="text-xl font-serif">{selected.full_name}</h3><p>{selected.message}</p><label>Stage<select name="status" defaultValue={selected.status}>{stages.map(s=><option key={s}>{s}</option>)}</select></label><label>Assigned team member<select name="assigned_to" defaultValue={selected.assigned_to??''}><option value="">Unassigned</option>{data.members?.map(m=><option key={m.user_id} value={m.user_id}>{m.role} · {m.user_id.slice(0,8)}</option>)}</select></label><label>Appointment ID (optional)<input name="appointment_id" defaultValue={selected.appointment_id??''}/></label><label>Add note<textarea name="note" maxLength={2000}/></label><button className="action-button" disabled={busy}>Save lead</button><button className="ml-4 underline" type="button" onClick={()=>setSelected(null)}>Close</button><h4 className="font-semibold">Activity</h4>{data.activities?.filter(a=>a.lead_id===selected.id).map(a=><p className="border-t pt-2 text-sm" key={a.id}>{a.description} · {new Date(a.created_at).toLocaleDateString()}</p>)}</form>}
    </>}
    {resource==='tasks'&&<><form className="flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void update({title:f.get('title'),due_at:f.get('due')?new Date(String(f.get('due'))).toISOString():null});}}><label className="flex-1">Follow-up task<input name="title" required minLength={2} maxLength={200}/></label><label>Due (your local time)<input type="datetime-local" name="due"/></label><button disabled={busy} className="action-button">Create task</button></form>{data.tasks?.length===0&&<p>No follow-up tasks yet.</p>}{data.tasks?.map(t=><div className="rounded-xl border bg-white p-4 flex justify-between gap-3" key={t.id}><div><strong>{t.title}</strong><p>{t.due_at?new Date(t.due_at).toLocaleString():'No due date'}</p></div><button disabled={busy} className="underline" onClick={()=>update({id:t.id,status:t.status==='open'?'completed':'open'})}>{t.status==='open'?'Mark complete':'Reopen'}</button></div>)}</>}
  </section>;
}
