'use client';
import { api } from '@/lib/api-client';
import { useEffect, useState } from 'react';
type Member={user_id:string;email:string;role:string;staff_id:string|null;is_active:boolean};
type Team={members:Member[];providers:{id:string;name:string}[];role:string};
export function TeamManagement(){
 const [team,setTeam]=useState<Team|null>(null);const [message,setMessage]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0);
 useEffect(()=>{let active=true;api<Team>('/api/team').then(r=>{if(active)setTeam(r);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[revision]);
 async function save(input:unknown){setBusy(true);setError('');setMessage('');try{const r=await api<{message:string}>('/api/team',input);setMessage(r.message);setRevision(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'Update failed.');}finally{setBusy(false);}}
 const roles=team?.role==='owner'?['staff','receptionist','admin','owner']:['staff','receptionist'];
 return <section className="booking-form space-y-4 border rounded-xl bg-white p-5"><h3 className="font-serif text-2xl">Team and access</h3><p className="text-sm">Admins see all appointments and manage staff. Staff see their own appointments and manage their availability. Only owners manage administrator accounts. Removing access preserves booking history.</p>
 {error&&<p role="alert" className="text-red-800">{error}</p>}{message&&<p role="status">{message}</p>}{!team&&!error&&<p>Loading team…</p>}
 {team&&<><div className="space-y-3">{team.members.map(member=><form key={`${member.user_id}-${revision}`} className="rounded-lg border p-3 space-y-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save({action:'update',user_id:member.user_id,role:f.get('role'),staff_id:f.get('staff_id')||null,is_active:f.get('active')==='on'});}}><p className="font-semibold break-all">{member.email}</p><p className="text-xs">{member.is_active?'Active':'Access removed'}</p>
 {team.role==='owner'||!['owner','admin'].includes(member.role)?<><label>Role<select name="role" defaultValue={member.role}>{roles.map(role=><option key={role}>{role}</option>)}</select></label><label>Provider<select name="staff_id" defaultValue={member.staff_id??''}><option value="">No provider (administration only)</option>{team.providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="check-label"><input name="active" type="checkbox" defaultChecked={member.is_active}/>Active dashboard access</label><button className="action-button" disabled={busy}>Save access</button></>:<p className="text-sm">{member.role} — managed by owner</p>}</form>)}</div>
 <form className="space-y-3 border-t pt-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save({action:f.get('action'),email:f.get('email'),name:f.get('name'),role:f.get('role'),staff_id:f.get('staff_id')||null});}}><h4 className="font-semibold">Add team member</h4><label>Name<input name="name" required minLength={2} maxLength={120}/></label><label>Email<input name="email" type="email" required/></label><label>Account<select name="action"><option value="link">Link existing Supabase account</option><option value="invite">Invite new account by email</option></select></label><label>Role<select name="role">{roles.map(role=><option key={role}>{role}</option>)}</select></label><label>Provider<select name="staff_id"><option value="">Create provider for staff role</option>{team.providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><p className="text-xs">New providers start with bookings disabled. Configure services, location and working hours, then enable booking in provider settings.</p><button disabled={busy} className="action-button">{busy?'Saving…':'Add team member'}</button></form></>}
 </section>;
}
